#!/bin/sh

do_sync () {
	local OLD_LOC=`pwd`
	echo Syncing from ./$1 to $2/$1...
	cd $1
	rsync -rlptvz --delete --exclude="sync" --exclude="tests" --exclude="*~" --exclude=".htaccess" --exclude=".svn" --exclude=".*.sw?" --exclude="*.xcf" --rsh=/usr/bin/ssh ./ "$2/$1"
	cd $OLD_LOC
}

do_sync_all () {
	echo "Affirmative, Dave, I read you."
	for AREA in .; do
		do_sync $AREA "$1"
	done
}

do_lint () {
	local i=''
	local exclusion=''

	# Exclude directories and symlinks in ./lib - they come from elsewhere so
	# we don't bother linting them.
	for i in `ls ./lib`; do
		if [ -d "./lib/$i" -o -L "./lib/$i" ]; then
			exclusion="$exclusion -wholename ./lib/$i -prune -o"
		fi
	done

	for i in `find . $exclusion -name \*.php -o -name \*.inc`; do
		if ! php -l "$i"; then
			echo $i has errors.
			return 1
		fi
	done

	return 0
}

# Make sure that we're in the right directory.
cd `dirname $0`

case "$1" in
	lint)
	if do_lint; then
		echo All clean!
	fi
	;;

	purge-svn)
	echo Purging .svn directories...
	find . -name .svn -type d -exec rm -rf {} +
	echo Done!
	;;

	production)
	# Remove these three lines, and possibly edit the do_sync_all function.
	echo "You'll need to edit me before you even think about running me."
	exit 255
	do_sync_all "%%PROD_USER%%@%%PROD_SERVER%%:%%PROD_APPLICATION_PATH%%"
	;;

	test)
	# Remove these three lines, and possibly edit the do_sync_all function.
	echo "You'll need to edit me before you even think about running me."
	exit 255
	do_sync_all "%%TEST_USER%%@%%TEST_SERVER%%:%%TEST_APPLICATION_PATH%%"
	;;

	*)
	echo "I'm sorry Dave, I'm afraid I can't do that."
	exit 1
esac
